Process nodes asynchronously
home-assistant-libs/python-matter-server pull request #266
Opened 2023-04-13 04:33 UTC by ArturoGuerra

This will process node interviews and subscriptions asynchronously and block from running the task again until all queued nodes have been processed.

2023-04-13 04:42 UTC, ArturoGuerra commented
Also is there any reason we process nodes hourly? wouldn't that make it so anything that was offline during startup wait a whole hour before it can be used?

2023-04-13 04:55 UTC, MartinHjelmare commented on matter_server/server/device_controller.py
> +                    asyncio.create_task(self.interview_node(node_id))
We should probably still catch `NodeInterviewFailed` so we need a wrapping function that can do that and that we can schedule as a task.

2023-04-13 04:55 UTC, MartinHjelmare commented on matter_server/server/device_controller.py
> +            subscription_tasks.append(asyncio.create_task(self.subscribe_node(node_id)))
Same for `NodeNotResolving`.

2023-04-13 05:15 UTC, marcelveldt commented
I actually did that on purpose because the ResolveNode was a bit fragile when called simultane so interview them one by one at startup (if needed) and run a task every hour to check if there are any nodes that need a (re)interview.

So... this needs real proper testing. It would be great if the SDK can now handle multiple resolve and interviews commands at the same time  but in my experience that is not the case. 

Also for thread devices this causes A LOT of traffic so I am not a fan of doing this async unless we have some lock on the interview/read call

2023-04-13 05:45 UTC, marcelveldt commented
As discussed on discord: 
- semaphore for max 5 interviews/read requests at the same time
- assume that we now can call resolvenode multiple times simultanuous

2023-04-14 05:37 UTC, MartinHjelmare requested changes

2023-04-14 05:37 UTC, MartinHjelmare commented on matter_server/server/device_controller.py
> +        futures: list[asyncio.Future] = await asyncio.gather(
```suggestion
        results: list[Exception | None] = await asyncio.gather(
```

2023-04-14 05:37 UTC, MartinHjelmare commented on matter_server/server/device_controller.py
> +            len(futures),
```suggestion
            len(results),
```

2023-04-14 05:37 UTC, MartinHjelmare commented on matter_server/server/device_controller.py
> +        for future in futures:
```suggestion
        for result in results:
```

2023-04-14 05:37 UTC, MartinHjelmare commented on matter_server/server/device_controller.py
> +            if isinstance(future, Exception):
```suggestion
            if isinstance(result, Exception):
```

2023-04-14 06:14 UTC, MartinHjelmare approved these changes
Marcel should approve too.

2023-04-14 07:03 UTC, marcelveldt approved these changes
yes! well done!

2023-04-17 08:48 UTC, marcelveldt commented
works like a charm!

2023-04-17 08:48 UTC, merged